apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: beacon-prod
resources:
  - ../../base
configMapGenerator:
  - name: beacon-config
    literals:
      - "ENVIRONMENT=prod"
      - "APP_VERSION=#{Octopus.Release.Number}"
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: beacon/loan-product-service
    newName: k3d-beacon-registry:5000/loan-product-service
    newTag: "#{Octopus.Release.Number}"
  - name: beacon/eligibility-service
    newName: k3d-beacon-registry:5000/eligibility-service
    newTag: "#{Octopus.Release.Number}"
